Repository CBNU-OSSW-CommunityProgram/team-project, pull requests merged in 2021-09, with the labels that each got.

#31 [#14] Feat : VR - add curriculum(virtual-reality.js)
  src/data.js
  src/data/virtual-reality.js
Labels: 개발, 리팩토링

#22 [#16] Feat : Frontend - HTML, CSS, Javascript, React.js 커리큘럼 추가
  assets/frontend-developer/language/basic-tags.svg
  assets/frontend-developer/language/colors.svg
  assets/frontend-developer/language/destructuring.svg
  assets/frontend-developer/language/dom.svg
  assets/frontend-developer/language/events.svg
  assets/frontend-developer/language/flex.svg
  assets/frontend-developer/language/grid.svg
  assets/frontend-developer/language/objects.svg
  assets/frontend-developer/language/spread.svg
  assets/frontend-developer/language/syntax-css.svg
  assets/frontend-developer/language/syntax.svg
  assets/frontend-developer/reactjs/communication.svg
  assets/frontend-developer/reactjs/component.svg
  assets/frontend-developer/reactjs/controlled-noncontrolled-components.svg
  assets/frontend-developer/reactjs/event.svg
  assets/frontend-developer/reactjs/life-cycle.svg
  assets/frontend-developer/reactjs/mount.svg
  assets/frontend-developer/reactjs/unmount.svg
  assets/frontend-developer/reactjs/update.svg
  src/data/pwa.js
Labels: 개발, 리팩토링

#30 [#29] Feat : Frontend - Vue.js 커리큘럼 추가
  assets/frontend-developer/browser/blink.svg
  assets/frontend-developer/browser/breakpoints.svg
  assets/frontend-developer/browser/browser-engines.svg
  assets/frontend-developer/browser/console-api.svg
  assets/frontend-developer/browser/debugging.svg
  assets/frontend-developer/browser/developer-console.svg
  assets/frontend-developer/browser/gecko.svg
  assets/frontend-developer/browser/http.svg
  assets/frontend-developer/browser/polyfills.svg
  assets/frontend-developer/browser/specifications.svg
  assets/frontend-developer/browser/standardization.svg
  assets/frontend-developer/browser/tc39.svg
  assets/frontend-developer/browser/the-internet.svg
  assets/frontend-developer/browser/w3c.svg
  assets/frontend-developer/browser/webkit.svg
  assets/frontend-developer/browser/whatwg.svg
  assets/frontend-developer/language/add-to-homescreen.svg
  assets/frontend-developer/language/dom-manipulation.svg
  assets/frontend-developer/language/pointer-events.svg
  assets/frontend-developer/language/syntax-css.svg
  assets/frontend-developer/language/syntax.svg
  assets/frontend-developer/language/touch-events.svg
  assets/frontend-developer/reactjs/big-o-notation.svg
  assets/frontend-developer/reactjs/communication.svg
  assets/frontend-developer/reactjs/component.svg
  assets/frontend-developer/reactjs/controlled-nonControlled-components.svg
  assets/frontend-developer/reactjs/cost-model.svg
  assets/frontend-developer/reactjs/dynamic-parameters.svg
  assets/frontend-developer/reactjs/event-handling.svg
  assets/frontend-developer/reactjs/event.svg
  assets/frontend-developer/reactjs/first-cpu-idle.svg
  assets/frontend-developer/reactjs/first-meaningful-paint.svg
  assets/frontend-developer/reactjs/hook.svg
  assets/frontend-developer/reactjs/mount.svg
  assets/frontend-developer/reactjs/nested-routes.svg
  assets/frontend-developer/reactjs/order-of-growth.svg
  assets/frontend-developer/reactjs/pass-properties.svg
  assets/frontend-developer/reactjs/redux.svg
  assets/frontend-developer/reactjs/router.svg
  assets/frontend-developer/reactjs/space-complexity.svg
  assets/frontend-developer/reactjs/time-complexity.svg
  assets/frontend-developer/reactjs/unmount.svg
  assets/frontend-developer/reactjs/update.svg
  assets/frontend-developer/reactjs/useeffect.svg
  assets/frontend-developer/reactjs/useref.svg
  assets/frontend-developer/reactjs/usestate.svg
  assets/frontend-developer/vuejs/Mount-.svg
  assets/frontend-developer/vuejs/component.svg
  assets/frontend-developer/vuejs/create.svg
  assets/frontend-developer/vuejs/event-bus.svg
  assets/frontend-developer/vuejs/instance.svg
  assets/frontend-developer/vuejs/life-cycle.svg
  assets/frontend-developer/vuejs/mount.svg
  assets/frontend-developer/vuejs/nested-router.svg
  assets/frontend-developer/vuejs/router.svg
  assets/frontend-developer/vuejs/unmount.svg
  assets/frontend-developer/vuejs/update.svg
  src/data/pwa.js
Labels: 개발, 리팩토링

#50 [#49] Fix : develop - frontend file name error solving
  assets/frontend-developer/reactjs/controlled-nonControlled-components.svg
  assets/frontend-developer/reactjs/controlled-noncontrolled-components.svg
Labels: 버그

#54 [#53] Refactor : AI - theory file development
  assets/Artificial-Intelligence/theory/cnn.svg
  assets/Artificial-Intelligence/theory/deep-learning.svg
  assets/Artificial-Intelligence/theory/machine-learning.svg
  assets/Artificial-Intelligence/theory/natural-language-processing.svg
  assets/Artificial-Intelligence/theory/rnn.svg
  src/data/artificial-intelligence.js
Labels: 개발, 리팩토링

#56 [#55] Feat : AI - skills development
  assets/Artificial-Intelligence/skills/keras.svg
  assets/Artificial-Intelligence/skills/python.svg
  assets/Artificial-Intelligence/skills/pytorch.svg
  assets/Artificial-Intelligence/skills/tensorflow.svg
  assets/Artificial-Intelligence/skills/yolo-v5.svg
  assets/Artificial-Intelligence/theory/yolo-v5.svg
  src/data/artificial-intelligence.js
Labels: 개발, 리팩토링

#58 [#57] Feat : AI - project development
  assets/Artificial-Intelligence/project/ai-chatbot.svg
  assets/Artificial-Intelligence/project/autonomous-driving.svg
  assets/Artificial-Intelligence/project/development.svg
  assets/Artificial-Intelligence/project/image-classification.svg
  src/data/artificial-intelligence.js
Labels: 개발, 리팩토링

#61 [#40] Feat : 블록체인 설명 변경,추가
  assets/frontend-developer/reactjs/controlled-nonControlled-components.svg
  src/data/design-and-ux.js
Labels: 개발

#63 [#62] Feat : 블록체인 이미지 추가
  assets/block-chain/Application-field.svg
  assets/block-chain/Bitcoin.svg
  assets/block-chain/Decentral.svg
  assets/block-chain/Digital-Note.svg
  assets/block-chain/Mastercoin.svg
  assets/block-chain/Namecoin.svg
  assets/block-chain/Open-type.svg
  assets/block-chain/Payment-and-remittance.svg
  assets/block-chain/Peercoin.svg
  assets/block-chain/Smart-Contract-Loan-Investment-Trading.svg
  assets/block-chain/block-chain.svg
  assets/block-chain/explanation.svg
  assets/frontend-developer/reactjs/controlled-noncontrolled-components.svg
  src/data/design-and-ux.js
Labels: 개발

#65 [#64] Doc : readme - 문서작성
  README.md
  assets/block-chain/Application-field.svg
  assets/block-chain/Bitcoin.svg
  assets/block-chain/Decentral.svg
  assets/block-chain/Digital-Note.svg
  assets/block-chain/Mastercoin.svg
  assets/block-chain/Namecoin.svg
  assets/block-chain/Open-type.svg
  assets/block-chain/Payment-and-remittance.svg
  assets/block-chain/Peercoin.svg
  assets/block-chain/Smart-Contract-Loan-Investment-Trading.svg
  assets/block-chain/block-chain.svg
  assets/block-chain/explanation.svg
  assets/frontend-developer/reactjs/controlled-nonControlled-components.svg
  assets/frontend-developer/reactjs/controlled-noncontrolled-components.svg
  src/data/design-and-ux.js
Labels: 문서
